apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: api-test-listener
spec:
  triggers:
    - binding:
        name: api-test-pipeline-binding
      template:
        name: api-test-pipeline-template
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: api-test-pipeline-binding
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: api-test-pipeline-template
spec:
  params:
    - name: test_user
    - name: test_password
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: api-test-pipeline-run-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "echo-example"
      spec:
        pipelineRef:
          name: api-test-pipeline
        params:
          - name: test_user
            value: $(params.test_user)
          - name: test_password
            value: $(params.test_password)
          - name: PW_SERVICE_ID
            value: $(params.PW_SERVICE_ID)
          - name: PW_API_KEY
            value: $(params.PW_API_KEY)