apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  tasks:
    - name: task1
      taskRef:
        name: task1
    - name: task2
      taskRef:
        name: task2
