apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: api-test-pipeline
spec:
  params:
    - name: target_repo
      default: github.ibm.com/org-ids/private-worker-service
    - name: test_password
  tasks:
    - name: api-tests
      taskRef:
        name: api-tests-task
      params:
        - name: target_repo
          value: $(params.target_repo)
        - name: test_password
          value: $(params.test_password)