apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: api-test-pipeline
spec:
  params:
    - name: test_user
    - name: test_password
    - name: PW_SERVICE_ID
    - name: PW_API_KEY
  tasks:
    - name: api-tests
      taskRef:
        name: api-tests-task
      params:
        - name: test_user
          value: $(params.test_user)
        - name: test_password
          value: $(params.test_password)
        - name: PW_SERVICE_ID
          value: $(params.PW_SERVICE_ID)
        - name: PW_API_KEY
          value: $(params.PW_API_KEY)