apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  tasks:
    - name: api-tests
      taskRef:
        name: api-tests-task
      params:
        - name: target_repo
          value: $(params.target_repo)
        - name: test_password
          value: $(params.test_password)