apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  params:
    - name: quote
      description: simple quoted property
      default: TESTQUOTE
    - name: noquote
      description: simple unquoted property
      default: TESTNOQUOTE
    - name: environment_value
      description: A value from the pipeline level, trigger level or run level
      default: BLOOPER  
  tasks:
    - name: task1
      taskRef:
        name: task1
    - name: task2
      taskRef:
        name: task2
      params:
        - name: quote
          value: $(params.quote)
        - name: noquote
          value: $(params.noquote)
        - name: environment_value
          value: $(params.environment_value)
