apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task2
spec:
  steps:
    - name: task-two-step-one
      image: ubuntu
      command: ["bash", "-c"]
      args:
        - echo "test2";
          echo "$(params.test)";
          exit 0;
